#!/usr/bin/env bash

docker run --rm -it \
  -u $(id -u):$(id -g) \
  -v $(pwd):/app \
  -w /app \
  -e COMPOSER_HOME=/app/.composer \
  --entrypoint php \
  mock-server-dev:latest -d opcache.enable_cli=off -d zend_extension=xdebug.so /usr/local/bin/composer $@
