#!/usr/bin/env bash

DOCKER_ARG='-i'
if [ -z "$GITHUB_ACTIONS" ]; then
  DOCKER_ARG='-it'
fi

docker run --rm --init $DOCKER_ARG \
  -u "$(id -u):$(id -g)" \
  -v "$(pwd):/app" \
  -w /app \
  --entrypoint composer \
  mock-server:tool "$@"
