#!/usr/bin/env bash

if ! [ $GITHUB_ACTIONS ] ; then
  DOCKER_ARG='-t'
fi

docker run --rm -i ${DOCKER_ARG} \
  -u $(id -u):$(id -g) \
  -v $(pwd):/app \
  -w /app \
  --entrypoint composer \
  mock-server:tool $@
