#!/usr/bin/env php
<?php declare(strict_types=1);

require __DIR__ . '/../../../vendor/autoload.php';

use Amp\Http\Server\DefaultErrorHandler;
use Amp\Http\Server\Driver\SocketClientFactory;
use Amp\Http\Server\SocketHttpServer;
use Amp\Socket;
use Lav45\MockServer\Config;
use Lav45\MockServer\LoggerFactory;
use Lav45\MockServer\Test\Functional\Server\Component\Storage;
use Lav45\MockServer\Test\Functional\Server\RequestHandler;

(static function (): void {

    $config = new Config()
        ->port(getenv('PORT'))
        ->log(getenv('LOG_LEVEL'));

    $logger = new LoggerFactory('logger', $config->getLogLevel())->create();

    $clientFactory = new SocketClientFactory($logger);
    $serverSocketFactory = new Socket\ResourceServerSocketFactory();
    $server = new SocketHttpServer($logger, $serverSocketFactory, $clientFactory);
    $server->expose(new Socket\InternetAddress('0.0.0.0', $config->getPort()));

    $storage = new Storage();
    $requestHandler = new RequestHandler($storage);
    $errorHandler = new DefaultErrorHandler();
    $server->start($requestHandler, $errorHandler);

    $logger->info(\sprintf("Received signal %d, stopping HTTP server", Amp\trapSignal([SIGINT, SIGTERM])));

    $server->stop();

})();
