name: release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: "localhost:5000/"
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  release:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Checkout.
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push to local registry base image
        uses: docker/build-push-action@v6
        with:
          push: true
          network: host
          file: ./docker/base.Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.REGISTRY }}mock-server-base:latest

      - name: Build and push dev image
        uses: docker/build-push-action@v6
        with:
          push: true
          network: host
          file: ./docker/dev.Dockerfile
          platforms: ${{ env.PLATFORMS }}
          build-args: REGISTRY=${{ env.REGISTRY }}
          tags: ${{ env.REGISTRY }}mock-server-dev:latest

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install composer dependencies
        run: ./composer install --optimize-autoloader --classmap-authoritative --prefer-dist --no-progress --no-dev --ansi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          VERSION_SHORT=$(echo $VERSION | awk -F. '{print $1"."$2}')
          echo "VERSION_SHORT=$VERSION_SHORT" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: ./docker/prod.Dockerfile
          platforms: ${{ env.PLATFORMS }}
          build-args: REGISTRY=${{ env.REGISTRY }}
          tags: |
            lav45/mock-server:latest
            lav45/mock-server:${{ env.VERSION }}
            lav45/mock-server:${{ env.VERSION_SHORT }}
